name: CD Pipeline

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        env: 
          DOCKER_USER: shrihegde
        run: sudo docker pull shrihegde/titanic-fastapi:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f titanic-fastapi-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: shrihegde
        run: sudo docker run -it -d -p 8001:8001 --name titanic-fastapi-container shrihegde/titanic-fastapi:latest
